
services:
#  beecouple_nginx:
#    container_name: beecouple_nginx
#    image: nginx:stable-alpine
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/templates:/etc/nginx/templates
#    ports:
#      - "80:80"
#    depends_on:
#      - beecouple_frontend
#    networks:
#      - beecouple-network

  beecouple_frontend:
    container_name: beecouple_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - hakjoon-network



networks:
  hakjoon-network:
    driver: bridge
