// 취미 버튼
const favoriteCategories = {
  myHobbies: {
    title: "취미",
    items: [
      { id: 0, value: "공연/전시회 관람", label: "show" },
      { id: 1, value: "맛집체험", label: "food-menu" },
      { id: 2, value: "스포츠 관람", label: "baseball" },
      { id: 3, value: "드라이브", label: "car" },
      { id: 4, value: "독서", label: "book" },
      { id: 5, value: "요리", label: "bowl-hot" },
      { id: 6, value: "악기연주/노래", label: "music" },
      { id: 7, value: "봉사활동", label: "heart" },
      { id: 8, value: "글쓰기/블로그", label: "pencil" },
      { id: 9, value: "그림", label: "paint" },
      { id: 10, value: "웹서핑", label: "desktop" },
      { id: 11, value: "보드게임", label: "game" },
      { id: 12, value: "PC/모바일게임", label: "mobile" },
      { id: 13, value: "콘솔게임", label: "game" },
      { id: 14, value: "TV/영화", label: "tv" },
      { id: 15, value: "국내여행", label: "map" },
      { id: 16, value: "해외여행", label: "plane" },
      { id: 17, value: "테마파크", label: "star" },
      { id: 18, value: "사진촬영", label: "camera" },
      { id: 19, value: "동호회/소모임", label: "group" },
      { id: 20, value: "반려동물", label: "dog" },
      { id: 21, value: "아이템수집", label: "box" },
      { id: 22, value: "소품만들기", label: "brush" },
      { id: 23, value: "홈인테리아", label: "home" },
      { id: 24, value: "서예/캘리그라피", label: "pen" },
      { id: 25, value: "명상", label: "cloud" },
    ],
  },

  myExcises: {
    title: "운동",
    items: [
      { id: 0, value: "캠핑", label: "flame" },
      { id: 1, value: "홈트레이닝", label: "home" },
      { id: 2, value: "산책", label: "walk" },
      { id: 3, value: "수영", label: "swim" },
      { id: 4, value: "등산", label: "landscape" },
      { id: 5, value: "자전거", label: "cycling" },
      { id: 6, value: "스키/보드", label: "health" },
      { id: 7, value: "요가", label: "user-circle" },
      { id: 8, value: "필라테스", label: "body" },
      { id: 9, value: "헬스", label: "dumbbell" },
      { id: 10, value: "조깅/마라톤", label: "run" },
      { id: 11, value: "댄스", label: "music" },
      { id: 12, value: "복싱", label: "like" },
      { id: 13, value: "테니스", label: "tennis-ball" },
      { id: 14, value: "배드민턴", label: "shield-alt-2" },
      { id: 15, value: "볼링", label: "bowling-ball" },
      { id: 16, value: "골프", label: "circle" },
      { id: 17, value: "야구", label: "baseball" },
      { id: 18, value: "축구", label: "football" },
      { id: 19, value: "농구", label: "basketball" },
      { id: 20, value: "탁구", label: "rectangle" },
      { id: 21, value: "당구", label: "target-lock" },
      { id: 22, value: "낚시", label: "ship" },
      { id: 23, value: "클라이밍", label: "tree" },
      { id: 24, value: "크로스핏", label: "dumbbell" },
      { id: 25, value: "수상레포츠", label: "water" },
    ],
  },

  myInterestedInMovie: {
    title: "관심사 (영화)",
    items: [
      { id: 0, value: "드라마/로맨스", label: "heart" },
      { id: 1, value: "코미디", label: "laugh" },
      { id: 2, value: "액션", label: "bolt-circle" },
      { id: 3, value: "SF", label: "planet" },
      { id: 4, value: "역사", label: "book" },
      { id: 5, value: "애니메이션", label: "film" },
      { id: 6, value: "심리/스릴러", label: "brain" },
      { id: 7, value: "공포", label: "ghost" },
      { id: 8, value: "판타지", label: "magic-wand" },
      { id: 9, value: "뮤지컬", label: "music" },
      { id: 10, value: "스포츠", label: "trophy" },
      { id: 11, value: "전쟁", label: "shield" },
    ],
  },

  myInterestedInMusic: {
    title: "관심사 (음악)",
    items: [
      { id: 0, value: "락앤롤", label: "speaker" },
      { id: 1, value: "재즈", label: "zap" },
      { id: 2, value: "클래식", label: "piano" },
      { id: 3, value: "발라드/R&B", label: "heart" },
      { id: 4, value: "힙합/랩", label: "microphone" },
      { id: 5, value: "EDM", label: "music" },
      { id: 6, value: "컨트리", label: "radio" },
      { id: 7, value: "블루스", label: "guitar-amp" },
      { id: 8, value: "트로트", label: "disc" },
      { id: 9, value: "종교", label: "church" },
    ],
  },

  myInterestedInTV: {
    title: "관심사 (TV)",
    items: [
      { id: 0, value: "시사/뉴스", label: "news" },
      { id: 1, value: "다큐", label: "film" },
      { id: 2, value: "오락/예능", label: "tv" },
      { id: 3, value: "스포츠", label: "trophy" },
      { id: 4, value: "국내드라마", label: "home" },
      { id: 5, value: "해외드라마", label: "plane-take-off" },
    ],
  },
}

export { favoriteCategories }
