// 취미 버튼
const favoriteCategories = {
  hobbies: {
    title: "취미",
    items: [
      { id: 0, value: "공연/전시회 관람", label: "slideshow" },
      { id: 1, value: "맛집체험", label: "slideshow" },
      { id: 2, value: "스포츠 관람", label: "slideshow" },
      { id: 3, value: "드라이브", label: "slideshow" },
      { id: 4, value: "독서", label: "slideshow" },
      { id: 5, value: "요리", label: "slideshow" },
      { id: 6, value: "악기연주/노래", label: "slideshow" },
      { id: 7, value: "봉사활동", label: "slideshow" },
      { id: 8, value: "글쓰기/블로그", label: "slideshow" },
      { id: 9, value: "그림", label: "slideshow" },
      { id: 10, value: "웹서핑", label: "slideshow" },
      { id: 11, value: "보드게임", label: "slideshow" },
      { id: 12, value: "PC/모바일게임", label: "slideshow" },
      { id: 13, value: "콘솔게임", label: "slideshow" },
      { id: 14, value: "TV/영화", label: "slideshow" },
      { id: 15, value: "국내여행", label: "slideshow" },
      { id: 16, value: "해외여행", label: "slideshow" },
      { id: 17, value: "테마파크", label: "slideshow" },
      { id: 18, value: "사진촬영", label: "slideshow" },
      { id: 19, value: "동호회/소모임", label: "slideshow" },
      { id: 20, value: "반려동물", label: "slideshow" },
      { id: 21, value: "아이템수집", label: "slideshow" },
      { id: 22, value: "소품만들기", label: "slideshow" },
      { id: 23, value: "홈인테리아", label: "slideshow" },
      { id: 24, value: "서예/캘리그라피", label: "slideshow" },
      { id: 25, value: "명상", label: "slideshow" },
    ],
  },

  exercises: {
    title: "운동",
    items: [
      { id: 0, value: "캠핑", label: "slideshow" },
      { id: 1, value: "홈트레이닝", label: "slideshow" },
      { id: 2, value: "산책", label: "slideshow" },
      { id: 3, value: "수영", label: "slideshow" },
      { id: 4, value: "등산", label: "slideshow" },
      { id: 5, value: "자전거", label: "slideshow" },
      { id: 6, value: "스키/보드", label: "slideshow" },
      { id: 7, value: "요가", label: "slideshow" },
      { id: 8, value: "필라테스", label: "slideshow" },
      { id: 9, value: "헬스", label: "slideshow" },
      { id: 10, value: "조깅/마라톤", label: "slideshow" },
      { id: 11, value: "댄스", label: "slideshow" },
      { id: 12, value: "복싱", label: "slideshow" },
      { id: 13, value: "테니스", label: "slideshow" },
      { id: 14, value: "배드민턴", label: "slideshow" },
      { id: 15, value: "볼링", label: "slideshow" },
      { id: 16, value: "골프", label: "slideshow" },
      { id: 17, value: "야구", label: "slideshow" },
      { id: 18, value: "축구", label: "slideshow" },
      { id: 19, value: "농구", label: "slideshow" },
      { id: 20, value: "탁구", label: "slideshow" },
      { id: 21, value: "당구", label: "slideshow" },
      { id: 22, value: "낚시", label: "slideshow" },
      { id: 23, value: "클라이밍", label: "slideshow" },
      { id: 24, value: "크로스핏", label: "slideshow" },
      { id: 25, value: "수상레포츠", label: "slideshow" },
    ],
  },

  interestedWithMovie: {
    title: "관심사 (영화)",
    items: [
      { id: 0, value: "드라마/로맨스", label: "slideshow" },
      { id: 1, value: "코미디", label: "slideshow" },
      { id: 2, value: "액션", label: "slideshow" },
      { id: 3, value: "SF", label: "slideshow" },
      { id: 4, value: "역사", label: "slideshow" },
      { id: 5, value: "애니메이션", label: "slideshow" },
      { id: 6, value: "심리/스릴러", label: "slideshow" },
      { id: 7, value: "공포", label: "slideshow" },
      { id: 8, value: "판타지", label: "slideshow" },
      { id: 9, value: "뮤지컬", label: "slideshow" },
      { id: 10, value: "스포츠", label: "slideshow" },
      { id: 11, value: "전쟁", label: "slideshow" },
    ],
  },

  interestedWithMusic: {
    title: "관심사 (음악)",
    items: [
      { id: 0, value: "락앤롤", label: "slideshow" },
      { id: 1, value: "재즈", label: "slideshow" },
      { id: 2, value: "클래식", label: "slideshow" },
      { id: 3, value: "발라드/R&B", label: "slideshow" },
      { id: 4, value: "힙합/랩", label: "slideshow" },
      { id: 5, value: "EDM", label: "slideshow" },
      { id: 6, value: "컨트리", label: "slideshow" },
      { id: 7, value: "블루스", label: "slideshow" },
      { id: 8, value: "트로트", label: "slideshow" },
      { id: 9, value: "종교", label: "slideshow" },
    ],
  },

  interestedWithTV: {
    title: "관심사 (TV)",
    items: [
      { id: 0, value: "시사/뉴스", label: "slideshow" },
      { id: 1, value: "다큐", label: "slideshow" },
      { id: 2, value: "오락/예능", label: "slideshow" },
      { id: 3, value: "스포츠", label: "slideshow" },
      { id: 4, value: "국내드라마", label: "slideshow" },
      { id: 5, value: "해외드라마", label: "slideshow" },
    ],
  },
}

export { favoriteCategories }
